services:
  web:
    build: ./docker/web
    ports:
      - "80:80"
    tty: true
    volumes:
      - .:/var/www/piton
      - ./docker/web/apache-host.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/web/99-dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
      - ~/.ssh/id_rsa:/run/secrets/host_ssh_key

  db:
    platform: linux/arm64
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ~/.mysql-data/piton:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa